var express = require('express');
var bodyParser = require('body-parser')
var Honeybadger = require('honeybadger');

Honeybadger.logger.level = 'info';
Honeybadger.metricsInterval = 10000;

var app = express();

app.set('port', (process.env.PORT || 3000));

app.use(Honeybadger.metricsHandler);

app.use(Honeybadger.requestHandler);

app.use(bodyParser.urlencoded({ extended: false }));

app.get('/', function (req, res) {
  res.send('Looking to <a href="/fail?foo=bar&bar=baz">fail?</a>');
});

app.all('/fail', function (req, res) {
  Honeybadger.setContext({
    func: function() {},
    date: new Date(),
    user_id: '123',
    user_email: 'user@example.com',
    user_url: 'http://www.example.com/admin/user/123'
  });
  throw(new Error('This is a runtime error generated by the crywolf app.'));
});

app.listen(app.get('port'), function () {
  console.log('Example app listening on port 3000!');
});

app.use(Honeybadger.errorHandler);
