var express = require('express');
var bodyParser = require('body-parser')
var Honeybadger = require('honeybadger');

Honeybadger.logger.level = 'info';

var app = express();

app.set('port', (process.env.PORT || 3000));

app.use(bodyParser.urlencoded({ extended: false }));

app.get('/', function (req, res) {
  console.log(req.body);
  res.send('Looking to <a href="/fail?foo=bar&bar=baz&user_email=josh@honeybadger.io">fail?</a>');
});

app.all('/fail', function (req, res) {
  throw(new Error('This is a runtime error generated by the crywolf app.'));
});

app.listen(app.get('port'), function () {
  console.log('Example app listening on port 3000!');
});

app.use(Honeybadger.errorHandler);
